apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiosquefood3000-api
  labels:
    app: quiosque-food3000-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiosque-food3000-api
  template:
    metadata:
      labels:
        app: quiosque-food3000-api
    spec:
      containers:
      - name: quiosque-food3000-api
        image: felipetoshio/quiosquefood3000:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        resources:
          requests:
            cpu: "250m" 
          limits:
            cpu: "500m"